git:
  depth: 3
sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - ~/.yarn-cache
node_js:
- '7'
- '6'
- '4'
- '0.12'
- '0.10'
env:
  global:
    - PKG_CMD="npm"
before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
install:
  - $PKG_CMD install
script:
  - 'if [ -n "${LINT-}" ]; then $PKG_CMD run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then $PKG_CMD run ci ; fi'
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: PKG_CMD="yarn"
      before_install: npm i -g yarn
    - node_js: "node"
      env: LINT=true
